version: '3.3'
services:
  app:
    build: ./searchapp
    ports:
      - "80:8000"
    depends_on:
      - postgres
      - elasticsearch
    volumes:
      - ./searchapp/:/searchapp/
    command: python manage.py runserver 0.0.0.0:8000
    environment: 
      - DB_HOST=postgres
      - DB_PORT=5432
      - ES_HOST=elasticsearch:9200
    links:
      - postgres:postgres
      - elasticsearch:elasticsearch

  postgres:
    image: postgres:latest
    environment: 
      - POSTGRES_DB=searchappdb
      - POSTGRES_USER=searchappuser
      - POSTGRES_PASSWORD=!searchapppass#
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5437:5432

  elasticsearch:
      image: bitnami/elasticsearch:latest
      container_name: es01
      environment:
        - node.name=es01
        - cluster.name=es-docker-cluster
        - cluster.initial_master_nodes=es01
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - esdata:/usr/share/elasticsearch/data
      ports:
        - 9200:9200

volumes:
  esdata:
    driver: local
  pgdata:
