version: '3.3'
services:
  app:
    container_name: searchapp
    build: ./searchapp
    ports:
      - "80:8000"
    depends_on:
      - postgres
      - elasticsearch
    volumes:
      - ./searchapp/:/searchapp/
    command: python manage.py runserver 0.0.0.0:8000
    environment: 
      - DB_HOST=postgres
      - DB_PORT=5432
      - ES_HOST=elasticsearch:9200
    links:
      - postgres:postgres

  postgres:
    image: postgres:latest
    container_name: searchapp-postgres
    environment: 
      - POSTGRES_DB=searchappdb
      - POSTGRES_USER=searchappuser
      - POSTGRES_PASSWORD=!searchapppass#
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5437:5432

  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
      environment:
        - discovery.type=single-node
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - esdata:/usr/share/elasticsearch/data
      ports:
        - 9200:9200

volumes:
  esdata:
    driver: local
  pgdata:
    driver: local
