# Generated by Django 3.1.1 on 2020-09-24 02:17
import os
import time
from django.conf import settings
from django.db import connection, migrations

def load_initial_data(apps, schema_editor):
        file_path = os.path.join(settings.BASE_DIR, 'db_script/codinghw2.sql')
        sql_statements = open(file_path).readlines()
        per_batch = 50000
        first = 0
        last = per_batch
        batch_num = len(sql_statements) // per_batch
        last_batch = len(sql_statements) % per_batch
        if last_batch > 0:
            batch_num += 1
        for batch in range(0, batch_num):
            print('--batch', batch)
            if batch == (batch_num):
                sql_statement = sql_statements[first:]
            else:
                sql_statement = sql_statements[first:last]

            with connection.cursor() as c:
                c.execute(''.join(sql_statement))

            first = last
            last += per_batch
            time.sleep(5)


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data)
    ]
