INSERT INTO zztemp_codinghw2 (text1,text2) VALUES (N'⭐ No.1 AMAZING Nottingham Experience ⭐', N'⭐ No.1 AMAZING Nottingham Experience ⭐, Nottingham, GB');
INSERT INTO zztemp_codinghw2 (text1,text2) VALUES (N'- SP Hotels - Apartment am Nützenberg', N'- SP Hotels - Apartment am Nützenberg, Wuppertal, DE');
INSERT INTO zztemp_codinghw2 (text1,text2) VALUES (N'- SP Hotels - City-Apartment', N'- SP Hotels - City-Apartment, Wuppertal, DE');
INSERT INTO zztemp_codinghw2 (text1,text2) VALUES (N' Luxury apartment in historic Bo-Kaap', N' Luxury apartment in historic Bo-Kaap, Cape Town, ZA');
INSERT INTO zztemp_codinghw2 (text1,text2) VALUES (N' Luxury Apartment near Battersea Power Station', N' Luxury Apartment near Battersea Power Station, London, GB');
INSERT INTO zztemp_codinghw2 (text1,text2) VALUES (N' Villa Next To The Beach With Panoramic View', N' Villa Next To The Beach With Panoramic View, Messini, GR');
INSERT INTO zztemp_codinghw2 (text1,text2) VALUES (N'"Andrioli Terrasse" by Nestor&Jeeves', N'"Andrioli Terrasse" by Nestor&Jeeves, Nice, FR');
INSERT INTO zztemp_codinghw2 (text1,text2) VALUES (N'"b" As You Are 3 Bedroom Home', N'"b" As You Are 3 Bedroom Home, Port Bolivar, TX, US');
INSERT INTO zztemp_codinghw2 (text1,text2) VALUES (N'"Côte D''Azur Design" by Nestor&Jeeves', N'"Côte D''Azur Design" by Nestor&Jeeves, Nice, FR');
INSERT INTO zztemp_codinghw2 (text1,text2) VALUES (N'"Côté Jardin" by Nestor&Jeeves', N'"Côté Jardin" by Nestor&Jeeves, Nice, FR');
